[package]
name = "aleph"
version = "0.0.40"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.210", features = ["derive"]}
serde_json = "1.0.128"
